#!/bin/env python
#
# Take a "snapshot" of a directory.
#
# The directory is renamed as a snapshot, and replaced by a copy containing
# softlinks to all the content.
#
import os.path

from snapit import snapshot


def _make_parser():
    import argparse
    parser = argparse.ArgumentParser(
        description='Snapshot a directory.')
    parser.add_argument('current', type=str,
                        help='Directory with content to snapshot.')
    parser.add_argument('--name', '-n', type=str, default=None,
                        help=('Name for snapshot [default = a timestamp].'))
    parser.add_argument('--verbose', '-v', action="store_true",
                        help=('Print details.'))
    parser.add_argument('--dry-run', action="store_true",
                        help=('Do nothing, but show what would happen.'))
    return parser


if __name__ == '__main__':
    parser = _make_parser()
    args = parser.parse_args()

    dryrun = args.dry_run
    verbose = args.verbose or dryrun
    path = args.current
    path = os.path.abspath(path)
    snapshot(current_path=path,
             snapshot_name=args.name,
             verbose=verbose, dryrun=dryrun)
